name: MaintainableCSS — это подход к написанию модульного, расширяемого и конечно же, поддерживаемого CSS кода. | By Adam Silver
markdown: kramdown
url: http://maintainablecss.ru
include: ['_pages']
collections:
  chapters:
    output: true
    permalink: /:collection/:title/
description: MaintainableCSS это подход к написанию модульного, расширяемого и конечно же, поддерживаемого CSS кода.
